### ISSUE TITLE
Merge solutions to main branch

### ISSUE THREAD

**Issue by SzilvasiPeter** [evoRegression/Regression#9]
Merge all side branches to main branch

# Tasks

## DataProvider
- [x] #28
- [x] #29
- [x] #30
- [x] #11 

## DataModel
- [x] #31
- [x] #32
- [x] #33
- [x] #11

**Comment by SzilvasiPeter** [comment]
- [ ] Work in the feedbacks
- [ ] Merge the solution to the main
- [ ] Lift out necessary part to **LinearRegression** solution
